import React, { useEffect, useState } from "react";
import { createPortal } from "react-dom";
import { call, type Gate, type Project, type Workflow } from "./api";
import { stageLabel, when } from "./labels";
import { errorText, facePreviewMode } from "./model";
import { Panel, useAction, useLoad } from "./ui";
import { FacePreviewView } from "./face-preview";

type RecolorTier = { id: string; label: string; chosen: boolean };
type RecolorImage = { id: string; tier: string; outfit: string | null; outfitLabel: string | null; chosen: boolean; sha256: string; width: number; height: number };
type RecolorPreview = { status: "ready"; source: "unity"; artifactHash: string; previewSha256: string; chosenTier: string; generatedAt?: string; tiers: RecolorTier[]; images: RecolorImage[] }
  | { status: "missing"; reason: string };
type DeliveryPhoto = { id: string; label: string; sha256: string; width: number; height: number };
type DeliveryPhotos = { status: "ready"; source: "unity"; buildHash: string; previewSha256: string; generatedAt?: string; photos: DeliveryPhoto[] }
  | { status: "missing"; reason: string };
type Read = { id: string; previewSha256: string; sha256: string; dataUrl: string };

/** Where a picture set came from and when it was recorded: the same line for all three stages. */
function SourceLine({ generatedAt }: { generatedAt?: string }) {
  return <p className="muted">来源：Unity 渲染{generatedAt ? ` · 生成于 ${when(generatedAt)}` : ""}。</p>;
}

/**
 * One candidate at its own pixel size, inside the application (F27f). A desktop host (Tauri / Wry) drops new windows and
 * Chromium refuses a top-level navigation to a `data:` URL, so the `target="_blank"` link this replaces was a control
 * that changed nothing — a dead button by D-42, and the person reading it as "查看原图" had no way to tell. The layer
 * draws the same data URL the thumbnail already bound and verified: no second read, no new window, no re-encode.
 *
 * The picture is never scaled — it keeps its bound pixel size and the layer scrolls in both directions when it is
 * larger than the window — so what a person compares here is the evidence itself, at the resolution it was rendered.
 * It closes with its own button, with Escape, or by clicking the backdrop.
 *
 * It is portalled to the document body: below 1100px the two columns take turns and the column this card lives in is
 * `display: none` while the other one shows, which would take an in-tree overlay off the screen with it. An overlay
 * that covers the window cannot belong to a column that can be hidden.
 */
function NativeSizeViewer({ caption, src, width, height, onClose }: {
  caption: string; src: string; width: number; height: number; onClose: () => void;
}) {
  useEffect(() => {
    const onKey = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [onClose]);
  return <div className="native-view-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}>
    <div className="native-view" role="dialog" aria-modal="true" aria-label={`${caption}原始分辨率`}>
      <div className="native-view-head">
        <b>{caption}</b>
        <span className="muted">原始分辨率 {width}×{height}</span>
        <button type="button" onClick={onClose}>关闭</button>
      </div>
      <div className="native-view-scroll">
        <img className="native-view-image" data-native-size="true" src={src} alt={`${caption}原始分辨率图片`} width={width} height={height} />
      </div>
    </div>
  </div>;
}

/** The pictures are read back as a set: a version that changed, a short batch or a different byte all withdraw them. */
function readSet<T extends { id: string; sha256: string }>(listed: T[], reads: Read[], previewSha256: string, label: string): Record<string, string> {
  if (reads.length !== listed.length || new Set(reads.map(read => read.id)).size !== reads.length)
    throw new Error(`${label}清单不完整，请刷新。`);
  return Object.fromEntries(listed.map(item => {
    const read = reads.find(candidate => candidate.id === item.id);
    if (!read || read.previewSha256 !== previewSha256 || read.sha256 !== item.sha256 || !read.dataUrl.startsWith("data:image/png;base64,"))
      throw new Error(`${label}版本不一致，请刷新制作进度。`);
    return [item.id, read.dataUrl] as const;
  }));
}

/**
 * The evidence a colour decision needs before its buttons: the candidates the recolour stage rendered in Unity, one per
 * tier × outfit, with the tier the plan chose marked. Nothing here is generated by the interface: a missing or
 * version-mismatched set removes the approval instead of asking the person to approve text (信息包装规范 §7).
 *
 * `compact` is the decision card's use of it (F27b): the chosen tier on each outfit, its source and time, and a pointer
 * at the full grid. The whole candidate grid belongs to the scene preview card beside the decision, and drawing it
 * twice buried the approval below the docked change-request box; the evidence rule is met by the strip together with
 * that always-available card, and a version that does not match still withdraws the approval.
 */
export function RecolorPreviewView({ projectId, workflowId, refresh, expectedHash, approve, compact = false, onlyWhenReady = false, stripOnly = false }: {
  projectId: string; workflowId: string; refresh: number; expectedHash?: string;
  approve?: { gate: string; label: string; success: string; expectedHash: string; expectedInputs?: Record<string, string>; changed: () => void };
  compact?: boolean; onlyWhenReady?: boolean; stripOnly?: boolean;
}) {
  const { busy, run } = useAction();
  const [preview, error] = useLoad<RecolorPreview | null>("project.recolor.preview", refresh, null,
    { projectId, workflowId, expectedHash: expectedHash ?? "" });
  const [images, setImages] = useState<Record<string, string>>({}), [imageError, setImageError] = useState("");
  const [loaded, setLoaded] = useState<Record<string, boolean>>({});
  // The candidate opened for a closer look (F27f), or null. It holds the already-verified data URL, never a new read, and
  // the binding it was opened under (F37): the layer is only drawn while that binding and those same bytes are still the
  // evidence on screen, so a version that moved on, a failed re-read or a withdrawn picture cannot leave it up showing a
  // picture the thumbnails and the approval have already dropped.
  const [viewing, setViewing] = useState<{ id: string; binding: string; caption: string; src: string; width: number; height: number } | null>(null);
  const version = preview?.status === "ready" ? preview.previewSha256 : "";
  const ready = preview?.status === "ready" ? preview : null;
  const chosen = ready?.tiers.find(tier => tier.chosen);
  // The recipe's first tier is the plan's original values (recolor.py TIERS[0] = 方案原值), so it is the before side of
  // the comparison. No separate pre-recolour render exists, and this view never invents one.
  const original = ready?.tiers[0];
  // The strip's tier is the plan's chosen one; a recipe that marks none falls back to the first, without the marker.
  const stripTier = chosen ?? original;
  // What this view asks the Runtime for and draws: the whole grid, or only the chosen tier's row in the compact strip.
  const listed = ready ? (compact && stripTier ? ready.images.filter(image => image.tier === stripTier.id) : ready.images) : [];
  const listedKey = listed.map(image => image.id).join(",");
  // What an open layer may keep showing: this project, this Workflow, the artifact version and the digest of the picture
  // list it was opened from. Any one of them changing withdraws the layer (F37) — the layer is the evidence, so it cannot
  // outlive the set the thumbnails and the approval are bound to.
  const evidenceBinding = [projectId, workflowId, ready?.artifactHash ?? "", ready?.previewSha256 ?? "", listedKey].join("|");
  useEffect(() => {
    let live = true; setImages({}); setLoaded({}); setImageError("");
    if (preview?.status === "ready" && listedKey) {
      const wanted = new Set(listedKey.split(","));
      const read = preview.images.filter(image => wanted.has(image.id));
      void (async () => {
        const reads = await call<Read[]>("project.recolor.preview.images", { projectId, workflowId, expectedHash,
          previewSha256: preview.previewSha256, ids: read.map(image => image.id) }, 300_000);
        return readSet(read, reads, preview.previewSha256, "候选图");
      })().then(read => { if (live) setImages(read); }).catch(reason => { if (live) setImageError(errorText(reason)); });
    }
    return () => { live = false; };
  }, [projectId, workflowId, version, refresh, expectedHash, listedKey]);
  // A picture that failed to display is withdrawn: the thumbnails go, and so does a layer already open on them (F37).
  const revoke = (reason: unknown) => { setImages({}); setLoaded({}); setImageError(errorText(reason)); setViewing(null); };
  const allLoaded = Boolean(listed.length && listed.every(image => loaded[image.id]));
  const bound = Boolean(ready && approve && ready.artifactHash === approve.expectedHash);
  const outfitOrder = ready ? [...new Set(ready.images.map(image => image.outfit))] : [];
  const outfitLabel = (outfit: string | null) => ready?.images.find(image => image.outfit === outfit)?.outfitLabel ?? "当前服装";
  const tierLabel = (tier: RecolorTier) => `${tier.id} 档${tier.label ? `（${tier.label}）` : ""}`;
  const compares = Boolean(ready && original && chosen && original.id !== chosen.id);
  // Open the bound picture, never a fresh copy of it: the layer shows the same bytes the thumbnail verifies on load. It
  // records the binding it was opened under, so what it may keep showing is decided by the evidence, not by this click.
  const openOriginal = (image: RecolorImage, caption: string) => {
    const src = images[image.id];
    if (src) setViewing({ id: image.id, binding: evidenceBinding, caption, src, width: image.width, height: image.height });
  };
  const cell = (image: RecolorImage, caption: string) => <figure style={{ margin: 0 }}>
    <button type="button" className="evidence-open" data-evidence-image="true" aria-label={`${caption}原始分辨率图片`}
      onClick={() => openOriginal(image, caption)}>
      <img src={images[image.id]} alt={`${caption}（Unity 渲染）`}
        onLoad={() => setLoaded(current => ({ ...current, [image.id]: true }))}
        onError={() => revoke(new Error("候选图无法显示，请重新读取后再决定。"))}
        style={{ width: "100%", height: "auto" }} width={image.width} height={image.height} />
    </button>
    <figcaption>{caption}</figcaption>
  </figure>;
  const choose = () => void run("approve", async () => {
    if (!ready || !approve) return;
    if (ready.artifactHash !== approve.expectedHash) throw new Error("候选图对应的版本已变化，请刷新后再决定。");
    await call("gate.decide", { gate: approve.gate, approve: true, note: "经 GUI 批准当前版本", expectedHash: approve.expectedHash,
      expectedInputs: approve.expectedInputs, expectedPreviewSha256: ready.previewSha256 }, 300_000);
    approve.changed();
  }, approve?.success);
  const body = <>
    <p className="reason">{compact
      ? "以下缩略图由 Unity 在制作工程里渲染（方案选定档 × 每套服装，同机位、同布光），是候选效果的来源依据，不是概念图。"
      : "以下图片由 Unity 在制作工程里渲染（每档 × 每套服装，同机位、同布光），是候选效果的来源依据，不是概念图。"}</p>
    {error || imageError ? <div className="banner warn">{error || imageError} 没有可核对的候选图时不能批准配色。</div>
      : preview?.status === "missing" ? <div className="banner warn">{preview.reason}你也可以在对话里说明想改的颜色或档位。</div>
      : !ready || !Object.keys(images).length ? <p>正在读取 Unity 渲染的候选图…</p>
      : <>
        <SourceLine generatedAt={ready.generatedAt} />
        {chosen ? <p>方案选定档：<b>{tierLabel(chosen)}</b>。图上是选定档落到材质后的结果；要换档，请在修改要求里写明档位。</p> : null}
        {compact ? <>
          {/* The condensed evidence: one thumbnail per outfit of the tier the plan chose, with the marker on it. */}
          <div className="evidence-strip">
            {listed.map(image => <figure key={image.id}>
              <button type="button" className="evidence-open" data-evidence-image="true"
                aria-label={`${outfitLabel(image.outfit)}原始分辨率图片`} onClick={() => openOriginal(image, outfitLabel(image.outfit))}>
                <img src={images[image.id]} alt={`${outfitLabel(image.outfit)} 的${stripTier ? tierLabel(stripTier) : ""}缩略图（Unity 渲染）`}
                  onLoad={() => setLoaded(current => ({ ...current, [image.id]: true }))}
                  onError={() => revoke(new Error("候选图无法显示，请重新读取后再决定。"))}
                  width={image.width} height={image.height} />
              </button>
              <figcaption>{outfitLabel(image.outfit)}{image.chosen ? <span className="pill ok">方案选定档</span> : null}</figcaption>
            </figure>)}
          </div>
          <p className="muted">完整候选与前后对比见右侧 Unity 场景预览。</p>
        </> : null}
        {compares && !compact ? <p>前后对比用<b>{tierLabel(original!)}</b>与<b>{tierLabel(chosen!)}</b>并排（同一机位）；这是方案原值档，不是另外渲染的未改色图。</p> : null}
        {!compact ? <div style={{ display: "grid", gridTemplateColumns: `auto repeat(${outfitOrder.length}, minmax(0, 1fr))`, gap: 12, alignItems: "start" }}>
          <div />
          {outfitOrder.map(outfit => <div key={outfit ?? "original"} className="muted">{outfitLabel(outfit)}</div>)}
          {ready.tiers.map(tier => <React.Fragment key={tier.id}>
            <div>{tierLabel(tier)}{tier.chosen ? <span className="pill ok">方案选定档</span> : null}</div>
            {outfitOrder.map(outfit => {
              const image = ready.images.find(item => item.tier === tier.id && item.outfit === outfit);
              return <div key={`${tier.id}:${outfit ?? "original"}`}>{image ? cell(image, outfitLabel(outfit)) : <p className="muted">这一档没有这套服装的图</p>}</div>;
            })}
          </React.Fragment>)}
          {compares ? <>
            <div>前后对比</div>
            {outfitOrder.map(outfit => {
              const before = ready.images.find(item => item.tier === original!.id && item.outfit === outfit);
              const after = ready.images.find(item => item.chosen && item.outfit === outfit);
              return <div key={`compare:${outfit ?? "original"}`} style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 6 }}>
                {before && after ? <>{cell(before, `原值（${original!.id}）`)}{cell(after, `选定（${chosen!.id}）`)}</>
                  : <p className="muted">这一套没有可对比的两张图</p>}</div>;
            })}
          </> : null}
        </div> : null}
        {!compact ? <p className="muted">过滤与渲染方式：Unity 正交正面全身照，取景只依赖骨骼，因此各档与各套服装可以并排比较。图片出现只说明效果已经渲染出来；是否接受这个效果仍由你决定。</p> : null}
      </>}
    {approve && ready && !error && !imageError ? (allLoaded && bound ? <div className="actions">
      <button className="primary" disabled={Boolean(busy)} onClick={choose}>{busy === "approve" ? "正在提交…" : approve.label}</button>
    </div> : <p className="muted">{bound ? "这些图全部显示出来后才可以批准。" : "候选图与这个决定绑定的版本不一致，请刷新制作进度。"}</p>) : null}
  </>;
  // The decision card's strip is not a panel of its own: the card already frames it, and the nested panel's chrome pushed
  // the card's own buttons under the docked change-request box in a 900px window (F27b).
  // The layer covers the window, so it is drawn on the body rather than inside the column this card happens to sit in.
  // Binding it here rather than trusting the click is what keeps it from outliving its evidence (F37): it is drawn only
  // while the binding it was opened under still matches and the picture it shows is still the verified read of that id.
  // A changed project, Workflow, artifact version or picture list, a failed re-read, or a withdrawn picture closes it —
  // the old data URL is never left on screen as if it were still current.
  const shown = viewing && viewing.binding === evidenceBinding && images[viewing.id] === viewing.src ? viewing : null;
  // Once withdrawn it stays closed: a later re-read of the same bytes must not pop the layer back up unasked.
  useEffect(() => { if (viewing && !shown) setViewing(null); }, [viewing, shown]);
  const viewer = shown ? createPortal(<NativeSizeViewer caption={shown.caption} src={shown.src} width={shown.width} height={shown.height} onClose={() => setViewing(null)} />, document.body) : null;
  if (onlyWhenReady && (!ready || error || imageError || !Object.keys(images).length)) return null;
  if (stripOnly && ready && listed[0] && images[listed[0].id]) return <section className="preview-strip" aria-label="配色预览缩略条">
    <img src={images[listed[0].id]} alt="配色预览缩略图" width={listed[0].width} height={listed[0].height} />
    <span><b>配色效果</b><small>来源：Unity 渲染{ready.generatedAt ? ` · ${when(ready.generatedAt)}` : ""}</small></span>
  </section>;
  return compact ? <><section className="recolor-evidence" id="recolor-evidence" aria-label="配色候选图">{body}</section>{viewer}</>
    : <><Panel title="配色候选图" id="recolor-candidates">{body}</Panel>{viewer}</>;
}

/**
 * What the finished avatar looks like, per outfit, before it is uploaded: the photos the regression stage took of the
 * built avatar in each state. Read-only, bound to the current build, and labelled with its source.
 */
export function DeliveryPhotosView({ projectId, workflowId, refresh, compact = false, onlyWhenReady = false }: { projectId: string; workflowId: string; refresh: number; compact?: boolean; onlyWhenReady?: boolean }) {
  const [photos, error] = useLoad<DeliveryPhotos | null>("project.delivery.photos", refresh, null, { projectId, workflowId });
  const [images, setImages] = useState<Record<string, string>>({}), [imageError, setImageError] = useState("");
  const version = photos?.status === "ready" ? photos.previewSha256 : "";
  useEffect(() => {
    let live = true; setImages({}); setImageError("");
    if (photos?.status === "ready") {
      void (async () => {
        const reads = await call<Read[]>("project.delivery.photos.images", { projectId, workflowId,
          previewSha256: photos.previewSha256, ids: photos.photos.map(photo => photo.id) }, 300_000);
        return readSet(photos.photos, reads, photos.previewSha256, "成品照片");
      })().then(read => { if (live) setImages(read); }).catch(reason => { if (live) setImageError(errorText(reason)); });
    }
    return () => { live = false; };
  }, [projectId, workflowId, version, refresh]);
  const ready = photos?.status === "ready" ? photos : null;
  if (onlyWhenReady && (!ready || error || imageError || !Object.keys(images).length)) return null;
  if (compact) return <section className="preview-strip" aria-label="成品预览缩略条">
    {ready?.photos[0] && images[ready.photos[0].id] ? <>
      <img src={images[ready.photos[0].id]} alt={`${ready.photos[0].label}缩略图`} width={ready.photos[0].width} height={ready.photos[0].height} />
      <span><b>{ready.photos[0].label}</b><small>来源：Unity 渲染{ready.generatedAt ? ` · ${when(ready.generatedAt)}` : ""}</small></span>
      <span className="muted">点击查看场景</span>
    </> : null}
  </section>;
  return <Panel title="成品照片" id="delivery-photos">
    <p className="reason">以下照片由 Unity 在最终工程里按每套服装的实际穿戴状态拍摄（同机位、同布光）。上传前用它核对成品；它不能代替 VRChat 客户端实测。</p>
    {error || imageError ? <div className="banner warn">{error || imageError} 没有可核对的成品照片。</div>
      : photos?.status === "missing" ? <p className="muted">{photos.reason}</p>
      : !ready || !Object.keys(images).length ? <p>正在读取成品照片…</p>
      : <>
        <SourceLine generatedAt={ready.generatedAt} />
        <div style={{ display: "grid", gridTemplateColumns: `repeat(${Math.min(3, ready.photos.length)}, minmax(0, 1fr))`, gap: 12 }}>
          {ready.photos.map(photo => <figure key={photo.id} style={{ margin: 0 }}>
            <img src={images[photo.id]} alt={`${photo.label} 的成品照片`}
              onError={() => { setImages({}); setImageError("成品照片无法显示，请重新读取。"); }}
              style={{ width: "100%", height: "auto" }} width={photo.width} height={photo.height} />
            <figcaption>{photo.label}</figcaption>
          </figure>)}
        </div>
      </>}
  </Panel>;
}

/**
 * The work surface's preview cards (设计 08「右侧 角色与轮盘」; 目标架构 D4; 决定 D-121). The larger, always available
 * card is the Unity scene preview: the current version's latest valid render for the stage the Workflow is in — face
 * previews, the recolour candidates, or the finished outfit photos after delivery. It never collapses, and nothing is
 * drawn in it that a supervised Unity step did not render.
 *
 * D-121 splits this area into two cards with the smaller, collapsible「真实菜单预览」belonging to dev.1.1. That card is
 * deliberately absent here (no placeholder, no "coming soon"): `.preview-cards` is a wrapping row, so a later smaller
 * sibling sits beside this one without changing this card's structure.
 */
export function ScenePreview({ project, workflow, gates, refresh }: {
  project: Project; workflow: Workflow | null; gates: Gate[]; refresh: number;
}) {
  const recolor = gates.find(gate => gate.workflowId === workflow?.id && gate.preview === "recolor-candidates" && gate.artifactHash);
  const faceMode = facePreviewMode(workflow?.stages ?? []);
  const status = project.workflow?.status;
  const delivered = status === "upload_ready" || status === "client_verified";
  const stage = delivered ? "交付成品" : recolor ? "配色阶段" : faceMode ? "脸型阶段" : "还没有出图";
  const pending = workflow?.stages.find(item => item.status !== "passed" && item.status !== "not_applicable");
  return <section className="preview-cards" aria-label="预览" id="preview-cards">
    <section className="preview-card" id="scene-preview">
      <div className="preview-head">
        <b>Unity 场景预览</b>
        <span className="muted">{stage}</span>
        <span className="muted">来源：Unity 渲染</span>
      </div>
      {delivered && workflow ? <DeliveryPhotosView projectId={project.id} workflowId={workflow.id} refresh={refresh} />
        : recolor && workflow ? <RecolorPreviewView projectId={project.id} workflowId={workflow.id} refresh={refresh} expectedHash={recolor.artifactHash} />
        : faceMode && workflow ? <FacePreviewView projectId={project.id} workflowId={workflow.id} refresh={refresh} candidateMode={faceMode === "candidates"} />
        : <Panel title="还没有可以看的图">
          <p className="muted">{workflow
            ? pending ? `「${stageLabel(pending.id)}」阶段还没有出图；出图后这里会显示当前版本的预览。` : "还没有可看的渲染图；有新的渲染后会显示在这里。"
            : "这个项目还没有开始制作流程；出图后这里会显示当前版本的角色预览。"}</p>
          <p className="muted">这里的画面全部来自 Unity 在受管工程里的静态渲染，不是实时 3D 预览。</p>
        </Panel>}
    </section>
  </section>;
}

/** A single, read-only evidence pointer shown above non-scene work tabs. */
export function PreviewStrip({ project, workflow, gates, refresh, onOpen }: {
  project: Project; workflow: Workflow | null; gates: Gate[]; refresh: number; onOpen: () => void;
}) {
  const recolor = gates.find(gate => gate.workflowId === workflow?.id && gate.preview === "recolor-candidates" && gate.artifactHash);
  const faceMode = facePreviewMode(workflow?.stages ?? []);
  const delivered = project.workflow?.status === "upload_ready" || project.workflow?.status === "client_verified";
  if (!workflow || (!recolor && !faceMode && !delivered)) return null;
  return <div className="preview-strip-button" role="button" tabIndex={0} onClick={onOpen}
    onKeyDown={event => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); onOpen(); } }} aria-label="打开场景预览">
    <span className="preview-strip-label">场景预览</span>
    {delivered ? <DeliveryPhotosView projectId={project.id} workflowId={workflow.id} refresh={refresh} compact onlyWhenReady />
      : recolor ? <RecolorPreviewView projectId={project.id} workflowId={workflow.id} refresh={refresh} expectedHash={recolor.artifactHash} compact onlyWhenReady stripOnly />
      : <FacePreviewView projectId={project.id} workflowId={workflow.id} refresh={refresh} candidateMode={faceMode === "candidates"} compact onlyWhenReady />}
  </div>;
}
