#!/usr/bin/env python3
# 【项目沉淀】通用工具（Harness 观测：project.initialize / assets.import）
# 适用素体：无关
# 工具链　：python3 标准库
# 可复用性：★★★ 换个单子直接能用
# 用途　　：只读测量工程初始化与解包结果，写 observation/0.1 到 --out；编译错误读本次 Run 的 Unity 日志。
# 用法　　：observe_project.py --out <文件>   （工程取 AVH_PROJECT_DIR，Run 目录取 AVH_RUN_DIR）
"""Independent measurements for the setup stage's project and import checks."""
import argparse
import glob
import hashlib
import importlib.util
import json
import os
import re
import sys
from pathlib import Path

TOOLS = Path(__file__).resolve().parent
if str(TOOLS) not in sys.path:
    sys.path.insert(0, str(TOOLS))
from plan import effective_inventory  # noqa: E402


def read_json(path):
    try:
        return json.loads(Path(path).read_text(encoding='utf-8'))
    except (OSError, ValueError):
        return None


class PackageContentMismatch(ValueError):
    def __init__(self, name, differences):
        self.differences = [dict(package=name, **item) for item in differences]
        summary = '；'.join(item['change'] + ' ' + item['path'] for item in differences[:8])
        super().__init__('实装包内容与冻结环境不一致：' + name + '；' + summary)


def valid_unity_meta(path):
    """A frozen metadata file can qualify only with an unambiguous Unity format and nonzero GUID."""
    try:
        text = path.read_text(encoding='utf-8-sig')
    except (OSError, UnicodeError):
        return False
    version = re.findall(r'^fileFormatVersion:\s*(\d+)\s*$', text, re.MULTILINE)
    guid = re.findall(r'^guid:\s*([^\r\n]+)\s*$', text, re.MULTILINE)
    return version == ['2'] and len(guid) == 1 and re.fullmatch(r'[0-9a-f]{32}', guid[0]) is not None and guid[0] != '0' * 32


def frozen_meta_guid_counts(packages):
    counts = {}
    for path in packages.rglob('*.meta'):
        try:
            text = path.read_text(encoding='utf-8-sig')
        except (OSError, UnicodeError):
            continue
        for guid in re.findall(r'^guid:\s*([0-9a-fA-F]{32})\s*$', text, re.MULTILINE):
            guid = guid.lower()
            counts[guid] = counts.get(guid, 0) + 1
    return counts


def generated_unity_meta(path, paired, relative):
    """Only minimal profiles actually generated by Unity for frozen paired source identities."""
    try:
        lines = [line.rstrip() for line in path.read_text(encoding='utf-8-sig').splitlines()]
    except (OSError, UnicodeError):
        return None
    if len(lines) < 2 or lines[0] != 'fileFormatVersion: 2' or not re.fullmatch(r'guid: [0-9a-f]{32}', lines[1]):
        return None
    guid = lines[1][6:]
    if guid == '0' * 32:
        return None
    if paired.is_dir():
        prefix, importer = ['folderAsset: yes'], 'DefaultImporter'
    elif paired.is_file() and relative == 'package.json':
        prefix, importer = [], 'PackageManifestImporter'
    elif paired.is_file() and paired.suffix.lower() in ('.txt', '.json'):
        prefix, importer = [], 'TextScriptImporter'
    elif paired.is_file() and paired.suffix.lower() == '.cginc':
        prefix, importer = [], 'ShaderIncludeImporter'
    else:
        return None
    expected = prefix + [importer + ':', '  externalObjects: {}', '  userData:', '  assetBundleName:', '  assetBundleVariant:']
    return {'guid': guid, 'importer': importer} if lines[2:] == expected else None


def installed_package_content(environment, installed, accepted, name, guid_counts=None, installed_guid_counts=None, generated=None):
    """Original source stays byte-authoritative; separately record proven Unity metadata derivations."""
    source, actual = environment.tree(accepted), environment.tree(installed)
    differences, derived = [], []
    if guid_counts is None:
        guid_counts = frozen_meta_guid_counts(accepted)
    if installed_guid_counts is None:
        installed_guid_counts = frozen_meta_guid_counts(installed)
    for path in sorted(set(source) | set(actual)):
        before, after = source.get(path), actual.get(path)
        if before == after:
            continue
        # A present source meta must still match exactly. Derivations never become accepted source.
        if before is None and after is not None and path.endswith('.meta'):
            paired = path[:-5]
            source_pair, actual_pair = accepted / paired, installed / paired
            profile = generated_unity_meta(installed / path, source_pair, paired)
            # The accepted byte tree does not freeze empty directories. Require a frozen descendant.
            frozen_directory = source_pair.is_dir() and any(key.startswith(paired + '/') for key in source)
            same_kind = (source_pair.is_file() and actual_pair.is_file() and source.get(paired) == actual.get(paired)) or (frozen_directory and actual_pair.is_dir())
            if profile and same_kind and guid_counts.get(profile['guid'], 0) == 0 and installed_guid_counts.get(profile['guid']) == 1:
                if generated is not None:
                    identity = environment.digest(source_pair) if source_pair.is_file() else hashlib.sha256(json.dumps(environment.tree(source_pair), sort_keys=True, separators=(',', ':')).encode()).hexdigest()
                    generated.append({'package': name, 'path': path, 'installedSha256': after,
                                      'pairedPath': paired, 'pairedKind': 'file' if source_pair.is_file() else 'directory',
                                      'sourcePairedSha256': identity, **profile,
                                      'reason': 'minimal-unity-generated-meta-for-frozen-source-without-meta'})
                continue
        if before is not None and after is None and path.endswith('.meta'):
            paired = path[:-5]
            valid = valid_unity_meta(accepted / path)
            guid = re.search(r'^guid:\s*([0-9a-f]{32})\s*$', (accepted / path).read_text(encoding='utf-8-sig'), re.MULTILINE).group(1) if valid else None
            if not (accepted / paired).exists() and not (installed / paired).exists() and valid and guid_counts.get(guid) == 1:
                derived.append({'package': name, 'path': path, 'sourceSha256': before,
                                'reason': 'frozen-valid-unity-meta-without-source-file-or-directory'})
                continue
        differences.append({'path': path, 'change': '新增' if before is None else '缺失' if after is None else '修改',
                            'sourceSha256': before, 'installedSha256': after})
    if differences:
        raise PackageContentMismatch(name, differences)
    return derived


def package_resolution(project, environment_tool, recipe_path):
    """Read installed VPM and UPM separately against the already accepted, byte-frozen baseline."""
    spec = importlib.util.spec_from_file_location('avh_frozen_environment', environment_tool)
    if spec is None or spec.loader is None:
        raise ValueError('缺少冻结的环境验证工具')
    environment = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(environment)
    recipe = environment.recipe_file(recipe_path)
    root = project / '_harness' / 'environment'
    # This is an independent reread of all accepted baseline bytes, not trust in its JSON receipt.
    environment.verify(root, recipe, environment.digest(recipe_path))
    baseline = root / 'baseline' / 'Packages'
    packages = project / 'Packages'
    environment.no_links(packages)
    declared = environment.read(packages / 'manifest.json')
    vpm = environment.read(packages / 'vpm-manifest.json')
    if declared != environment.read(baseline / 'manifest.json') or vpm != environment.read(baseline / 'vpm-manifest.json'):
        raise ValueError('工程依赖声明与已接受环境不一致')
    locked = vpm.get('locked')
    dependencies = declared.get('dependencies')
    upm = environment.read(packages / 'packages-lock.json').get('dependencies')
    if not isinstance(locked, dict) or not isinstance(dependencies, dict) or not isinstance(upm, dict):
        raise ValueError('缺少完整的依赖声明与解析锁')
    folders = {p.name: p for p in packages.iterdir() if p.is_dir() and (p / 'package.json').is_file()}
    expected = {p.name: p for p in baseline.iterdir() if p.is_dir() and (p / 'package.json').is_file()}
    if set(folders) != set(expected):
        raise ValueError('工程实装包集合与已接受环境不一致')
    metadata, derived_removals, generated_metadata = {}, [], []
    guid_counts = frozen_meta_guid_counts(baseline)
    installed_guid_counts = frozen_meta_guid_counts(packages)
    for name, folder in folders.items():
        actual = environment.read(folder / 'package.json')
        if actual.get('name') != name or actual.get('version') != environment.read(expected[name] / 'package.json').get('version'):
            raise ValueError('实装包身份或版本不一致：' + name)
        derived_removals.extend(installed_package_content(environment, folder, expected[name], name, guid_counts, installed_guid_counts, generated_metadata))
        if name in locked and actual.get('version') != locked[name].get('version'):
            raise ValueError('VPM 锁定版本与实装不一致：' + name)
        if any(dep not in locked for dep in actual.get('vpmDependencies', {})):
            raise ValueError('VPM 缺少锁定传递依赖：' + name)
        metadata[name] = actual
    if set(locked) - set(metadata):
        raise ValueError('VPM 缺少实装包')
    # Reachable UPM requirements include UPM dependencies declared by VPM packages. A prefix is never authority.
    requirements = dict(dependencies)
    for actual in metadata.values():
        for name, version in actual.get('dependencies', {}).items():
            if name not in requirements or environment.upm_version(version) > environment.upm_version(requirements[name]):
                requirements[name] = version
    builtin = recipe.get('builtinPackages', {})
    reachable = set(locked) | set(requirements)
    for name in list(requirements):
        entry = upm.get(name)
        if not isinstance(entry, dict):
            raise ValueError('UPM 缺少解析锁：' + name)
        if name in metadata:
            if name not in dependencies and not any(name in m.get('dependencies', {}) for m in metadata.values()):
                raise ValueError('UPM 实装包没有声明来源：' + name)
        elif name not in builtin:
            raise ValueError('UPM 依赖没有冻结的实装或内建来源：' + name)
    for name, entry in upm.items():
        if not isinstance(entry, dict):
            raise ValueError('UPM 解析锁格式错误')
        if name in metadata:
            if entry.get('source') != 'embedded' or entry.get('version') != 'file:' + name or entry.get('dependencies', {}) != metadata[name].get('dependencies', {}):
                raise ValueError('UPM 实装来源、路径或依赖与解析锁不一致：' + name)
            resolved_version = metadata[name]['version']
        elif name in builtin:
            if entry.get('source') != 'builtin' or entry.get('version') != builtin[name]:
                raise ValueError('UPM 内建来源或版本不一致：' + name)
            resolved_version = builtin[name]
        else:
            raise ValueError('UPM 解析锁包含未知包：' + name)
        if name in requirements and environment.upm_version(resolved_version) < environment.upm_version(requirements[name]):
            raise ValueError('UPM 解析版本不满足声明：' + name)
        for dep, version in entry.get('dependencies', {}).items():
            if dep not in upm:
                raise ValueError('UPM 缺少传递解析项：' + dep)
            actual_version = metadata[dep]['version'] if dep in metadata else builtin.get(dep)
            if actual_version is None or environment.upm_version(actual_version) < environment.upm_version(version):
                raise ValueError('UPM 传递依赖版本不满足声明：' + dep)
    pending = list(reachable)
    while pending:
        name = pending.pop()
        entry = upm.get(name)
        if not isinstance(entry, dict):
            raise ValueError('依赖闭包缺少解析项：' + name)
        for dep in entry.get('dependencies', {}):
            if dep not in reachable:
                reachable.add(dep)
                pending.append(dep)
    if set(upm) != reachable or set(metadata) - set(locked) - set(requirements):
        raise ValueError('UPM 实装或解析锁包含孤儿包')
    return {'vpm_locked_entries': len(locked), 'vpm_package_dirs': len(set(metadata) & set(locked)),
            'upm_embedded_packages': len(set(metadata) - set(locked)), 'package_resolution_consistent': True,
            'package_content_derived_removals': derived_removals,
            'package_content_generated_metadata': generated_metadata}


def vpm_import_closure(project, inventory, rows, plan=None):
    """Join each approved VPM entry with the registration, accepted pins, actual package and import record.

    The inventory says what was approved and the import record says what setup claimed; neither is evidence
    on its own. This re-reads the intake's registration, the accepted environment lock and the bytes in
    ``Packages/`` and requires all five to name the same identity and version. An entry with no record is an
    unimported item (it belongs in the pending list); a record that disagrees with any other source is a
    mapping error. Returns ``(unimported, inconsistent)``.
    """
    if plan is None:
        plan = json.loads(os.environ.get('AVH_PLAN') or '{}')
    inventory = effective_inventory(inventory, plan)
    wanted = [(item['item'], file['name'], item, file) for item in inventory.get('items', [])
              for file in item.get('files', []) if file.get('selected') and file.get('kind') == 'vpm']
    if not wanted:
        return [], []
    registration = read_json(project / '_harness' / 'intake' / 'vpm-requirements.json')
    requirements = registration.get('requirements') if isinstance(registration, dict) else None
    recorded_lock = read_json(project / '_harness' / 'environment' / 'environment-lock.json')
    pins = (recorded_lock.get('vpmRequirements') or {}).get('packages') if isinstance(recorded_lock, dict) else None
    identity = str(wanted[0][0])
    if not isinstance(requirements, list):
        return [], [identity + '：缺少或无法读取 VPM 依赖登记']
    if not isinstance(pins, list):
        return [], [identity + '：环境锁缺少项目 VPM 依赖 pin']
    unimported, inconsistent = [], []
    # Validate the product's complete approved source set once, then select only the current file's sources
    # in the per-file join below.
    approved_by_item = {}
    for item_id, name, item, file in wanted:
        entries = [entry for entry in (file.get('vpm') or []) if isinstance(entry, dict)] \
            or [entry for entry in (item.get('vpm') or []) if isinstance(entry, dict) and entry.get('member') == name]
        approved_by_item.setdefault(item_id, set()).update(
            entry.get('repository') for entry in entries if isinstance(entry.get('repository'), str))
    for item_id, approved in approved_by_item.items():
        item_pins = [pin for pin in pins if isinstance(pin, dict) and pin.get('item') == item_id]
        declared = []
        for pin in item_pins:
            repository = pin.get('repository')
            if not isinstance(repository, str) or not repository.startswith('https://'):
                inconsistent.append(item_id + '：已接受 pin 的来源不是 HTTPS 仓库 ' + str(pin.get('id')))
            elif repository not in approved:
                inconsistent.append(item_id + '：已接受 pin 的来源不是清点登记的仓库 ' + str(pin.get('id')))
            else:
                declared.append(pin)
        for repository in sorted(approved):
            if not any(pin.get('repository') == repository for pin in declared):
                inconsistent.append(item_id + '：清点登记了 VPM 依赖，但已接受环境没有对应仓库的 pin ' + repository)
    for item_id, name, item, file in wanted:
        entries = [entry for entry in (file.get('vpm') or []) if isinstance(entry, dict)] \
            or [entry for entry in (item.get('vpm') or []) if isinstance(entry, dict) and entry.get('member') == name]
        # A pin is not identified by its item alone. The repository is the other half of the approved source
        # key: a pin for this item that came from a repository the intake never approved is a different
        # dependency, and a plaintext one is not a fixed source at all. Matching only on the item accepted
        # both, so each pin is checked against the repositories the approved entries name, and each approved
        # repository has to be covered by a pin.
        approved = {entry.get('repository') for entry in entries if isinstance(entry.get('repository'), str)}
        item_pins = [pin for pin in pins if isinstance(pin, dict) and pin.get('item') == item_id
                     and pin.get('repository') in approved]
        declared = []
        for pin in item_pins:
            repository = pin.get('repository')
            if not isinstance(repository, str) or not repository.startswith('https://'):
                inconsistent.append(item_id + '：已接受 pin 的来源不是 HTTPS 仓库 ' + str(pin.get('id')))
            elif repository not in approved:
                inconsistent.append(item_id + '：已接受 pin 的来源不是清点登记的仓库 ' + str(pin.get('id')))
            else:
                declared.append(pin)
        for repository in sorted(approved):
            if not any(pin.get('repository') == repository for pin in declared):
                inconsistent.append(item_id + '：清点登记了 VPM 依赖，但已接受环境没有对应仓库的 pin ' + repository)
        if not approved and not item_pins:
            inconsistent.append(item_id + '：清点登记了 VPM 依赖，但已接受环境没有对应 pin')
        for entry in entries:
            # The registration row carries the approved bundle digest; the per-file entry carries only the
            # entry's spelling, so the digest is taken from the file the intake approved.
            matched = [row for row in requirements if isinstance(row, dict) and row.get('item') == item_id
                       and row.get('repository') == entry.get('repository')
                       and row.get('member') == entry.get('member')
                       and row.get('entry') == name
                       and row.get('sourceSha256') == file.get('sha256')]
            if len(matched) != 1:
                inconsistent.append(item_id + '：依赖登记与清点不一致 ' + str(entry.get('repository')))
        records = [row for row in rows if row.get('kind') == 'vpm' and row.get('item') == item_id and row.get('zip') == name]
        if not records:
            unimported.append((item_id, name))
            continue
        if len(records) != 1:
            inconsistent.append(item_id + '：VPM 导入记录重复')
            continue
        record = records[0]
        expected = sorted((pin.get('id'), pin.get('version')) for pin in declared)
        actual = sorted((dep.get('id'), dep.get('version')) for dep in (record.get('dependencies') or [])
                        if isinstance(dep, dict))
        if expected != actual:
            inconsistent.append(item_id + '：导入记录与已接受 pin 的映射不一致')
        if sorted(record.get('roots') or []) != sorted('Packages/' + str(pin.get('id')) for pin in declared):
            inconsistent.append(item_id + '：导入记录的包根与已接受 pin 不一致')
        for pin in declared:
            metadata = read_json(project / 'Packages' / str(pin.get('id')) / 'package.json')
            if not isinstance(metadata, dict) or metadata.get('name') != pin.get('id') \
                    or metadata.get('version') != pin.get('version'):
                inconsistent.append(item_id + '：已接受 pin 与实装包不一致 ' + str(pin.get('id')))
    return unimported, inconsistent


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--project', default=os.environ.get('AVH_PROJECT_DIR'))
    parser.add_argument('--out', required=True)
    parser.add_argument('--environment-tool', required=True)
    parser.add_argument('--environment-recipe', required=True)
    args = parser.parse_args()
    project, run = Path(args.project), Path(os.environ.get('AVH_RUN_DIR', ''))
    notes, metrics, proof = [], {}, {}

    metrics['project_version_file_present'] = (project / 'ProjectSettings' / 'ProjectVersion.txt').is_file()
    vpm = read_json(project / 'Packages' / 'vpm-manifest.json') or {}
    metrics['package_resolution_consistent'] = False
    try:
        measured = package_resolution(project, args.environment_tool, args.environment_recipe)
        # observation/0.1 metrics are scalars; keep complete independently measured byte identities in the same output.
        for name in ('package_content_derived_removals', 'package_content_generated_metadata'):
            proof[name] = measured.pop(name)
        metrics.update(measured)
        if any(proof.values()):
            notes.append('依赖内容独立证据：移除孤立元数据 ' + str(len(proof['package_content_derived_removals']))
                         + ' 项，生成元数据 ' + str(len(proof['package_content_generated_metadata'])) + ' 项；完整路径和 SHA256 见 proof')
    except (OSError, ValueError, KeyError, TypeError, AttributeError) as error:
        notes.append('依赖独立核验未通过：' + str(error))
        if isinstance(error, PackageContentMismatch):
            proof['package_content_differences'] = error.differences
    metrics['editor_dll_present'] = (project / 'Library' / 'ScriptAssemblies' / 'Assembly-CSharp-Editor.dll').is_file()
    logs = sorted(glob.glob(str(run / 'unity-*.log'))) if str(run) else []
    if logs:
        errors = [line.strip() for log in logs for line in Path(log).read_text(encoding='utf-8', errors='replace').splitlines()
                  if re.search(r'error CS\d{4}', line)]
        metrics['console_cs_errors'] = len(errors)
        if errors:
            notes.append('编译错误：' + ' | '.join(errors[:5]))
    else:
        metrics['console_cs_errors'] = None
        notes.append('本次 Run 没有 Unity 日志，无法判断编译错误')
    manifest = read_json(project / 'Packages' / 'manifest.json') or {}
    deps = manifest.get('dependencies', {})
    # 离线从 registry 装不回来的来源：file:、git、http(s)、ssh，或任何带 .git 的地址（如 …unity-mcp.git?path=…#v10）
    risky = [name for name, value in deps.items()
             if str(value).startswith(('file:', 'git', 'http:', 'https:', 'ssh:')) or '.git' in str(value)]
    metrics['file_or_git_dependencies'] = len(risky) if manifest else None
    if risky:
        notes.append(f'file:/git 依赖：{risky}')

    record = read_json(project / '_harness' / 'setup' / 'import.json')
    raw_inventory = read_json(project / '_harness' / 'intake' / 'inventory.json')
    plan = json.loads(os.environ.get('AVH_PLAN') or '{}')
    inventory = effective_inventory(raw_inventory or {}, plan) if raw_inventory is not None else None
    if record is None or inventory is None:
        metrics['unresolved_unpack_conflicts'] = None
        metrics['remaining_unopened_archives'] = None
        metrics['vpm_import_records_consistent'] = None
        notes.append('缺少 import.json 或 inventory.json')
    else:
        packages = record.get('packages', [])
        conflicts = sum(p.get('content_conflicts', 0) + len(p.get('guid_conflicts', [])) for p in packages)
        # The pending list is about every selected input, not only the .unitypackage ones. A VPM entry the
        # intake approved but setup never recorded would otherwise look like a clean import.
        vpm_unimported, vpm_inconsistent = vpm_import_closure(project, raw_inventory, packages, plan)
        for problem in vpm_inconsistent:
            conflicts += 1
            notes.append('VPM 依赖导入记录独立核验不一致：' + problem)
        metrics['vpm_import_records_consistent'] = not vpm_inconsistent
        for item in inventory.get('items', []):
            for selected in item.get('files', []):
                if not selected.get('selected') or selected.get('kind') != 'texture':
                    continue
                matches = [p for p in packages if p.get('kind') == 'texture' and p.get('item') == item['item']
                           and p.get('zip') == selected['name'] and p.get('projectPath') == selected.get('projectPath')
                           and p.get('sha256') == selected.get('sha256') and 'error' not in p]
                relative_path = selected.get('projectPath', '')
                expected = selected.get('sha256', '')
                target = project / relative_path
                valid_path = bool(re.fullmatch(r'Assets/_HarnessTextures/[a-f0-9]{64}\.(png|jpg)', relative_path))
                valid = False
                if valid_path and len(matches) == 1 and len(expected) == 64:
                    try:
                        if not any(p.is_symlink() for p in (project, project / 'Assets', target.parent, target)) and target.is_file():
                            with target.open('rb') as source:
                                valid = hashlib.file_digest(source, 'sha256').hexdigest() == expected
                    except OSError:
                        pass
                if not valid:
                    conflicts += 1
                    notes.append('独立纹理导入记录或实际内容不一致')
        metrics['unresolved_unpack_conflicts'] = conflicts
        wanted = [(item['item'], f['name'], pkg) for item in inventory.get('items', []) for f in item.get('files', [])
                  if f.get('selected') for pkg in f.get('packages', [])]
        done = {(p['item'], p['zip'], p.get('package')) for p in packages if 'error' not in p}
        remaining = [w for w in wanted if w not in done] + vpm_unimported
        leftovers = [str(p.relative_to(project)) for p in (project / 'Assets').rglob('*')
                     if p.suffix.lower() in ('.zip', '.unitypackage')] if (project / 'Assets').is_dir() else []
        metrics['remaining_unopened_archives'] = len(remaining) + len(leftovers)
        if remaining or leftovers:
            notes.append(f'未解开：{remaining}；工程里残留压缩包：{leftovers[:5]}')
    Path(args.out).write_text(json.dumps({'schema': 'observation/0.1', 'metrics': metrics, 'notes': notes, 'proof': proof},
                                         ensure_ascii=False, indent=2), encoding='utf-8')


if __name__ == '__main__':
    main()
