import {relocateProductionAssets} from './production-face-assets.ts';
import {randomUUID} from 'node:crypto';
import {existsSync,lstatSync,mkdirSync,readFileSync,writeFileSync} from 'node:fs';
import {join} from 'node:path';
import {execFileSync} from 'node:child_process';
import type {DatabaseSync} from 'node:sqlite';
import type {LocalConfig} from './config.ts';
import {projectRoot} from './archive/takeover.ts';
import {relativeInside} from './archive/scan.ts';
import {restoreRecordFiles} from './archive/restore-record.ts';
import {inTransaction} from './archive/facts.ts';
import {canonicalJson} from './pack-hash.ts';
import {sha256File} from './file-hash.ts';
import {hostPlatform} from './host-platform.ts';
import {aggregateWorkflow,buildAggregateInput} from './state/aggregate-input.ts';
import {artifactFiles,artifactFingerprint} from './workflow/artifacts.ts';
import {forkFrozenWorkflow,workflowSnapshot,verifyTools,type WorkflowSnapshot} from './workflow/runtime.ts';
import {activateFaceInput,inputSha256} from './workflow/inputs.ts';
import {withStateEvent} from './state/tx.ts';
import {managedPacks} from './managed-pack.ts';
import {frozenPackConfig} from './managed-pack-candidate.ts';
import {packTreeHash} from './pack-hash.ts';
import {manifestToolReferences} from './workflow/capabilities.ts';
import {preparationEvidenceContract} from './workflow/preparation-evidence.ts';
import {taskRedo} from './task-cli.ts';
import {copyProductionManifest,idleOnCadence,productionFilesAt,productionProjectIdle,type Continuation,type ProductionFile} from './production-face-continuation.ts';

export interface RebuildPreparation {
  schema:'production-preparation/0.2';sourceKind:'frozen_rebuild';checkpoint:'preserve'|'seed'|'prepare'|'reconcile'|'publish';
  source:string;destination:string;preservedRoot:string;sourceFiles:ProductionFile[];seedFiles:ProductionFile[];
  snapshot:WorkflowSnapshot;contractMode:'inherit'|'successor';sourceContractHash:string;
  candidateProjectId?:string;candidateWorkflowId?:string;report?:{hash:string;unknown:ProductionFile[];generated:ProductionFile[];candidateFiles:ProductionFile[]};
  resolutions?:{reportHash:string;eventSeq:number;retainOnly:string[]};
}
function conflict(message:string):never {throw Object.assign(new Error(message),{code:'CONFLICT'});}
const equal=(a:unknown,b:unknown)=>canonicalJson(a)===canonicalJson(b);
function save(db:DatabaseSync,row:Continuation,preparation:RebuildPreparation) {
  db.prepare("UPDATE production_continuation SET preparation_json=?,revision=revision+1 WHERE id=? AND state='preparing'")
    .run(JSON.stringify(preparation),row.id);
}

/** Generated bytes are exempt only when their persisted producer or archive receipt verifies. */
export function verifiedGeneratedFiles(db:DatabaseSync,projectId:string,source:WorkflowSnapshot,root:string):ProductionFile[] {
  const generated=new Map<string,string>();
  for(const receipt of restoreRecordFiles(db,projectId)) {
    const path=join(root,receipt.path);
    if(existsSync(path)&&sha256File(path)===inputSha256(receipt.content))generated.set(receipt.path,inputSha256(receipt.content));
  }
  const archivePath=join(root,'_harness/archive.json');
  if(existsSync(archivePath) && db.prepare("SELECT 1 FROM project_archive_write WHERE project_id=? AND status='verified' AND manifest_sha256=?").get(projectId,sha256File(archivePath))) {
    const manifest=JSON.parse(readFileSync(archivePath,'utf8'));
    generated.set('_harness/archive.json',sha256File(archivePath));
    for(const file of manifest.files??[])if(typeof file.path==='string'&&existsSync(join(root,file.path))&&sha256File(join(root,file.path))===file.sha256)
      generated.set(file.path,file.sha256);
  }
  const manualPath='_harness/face/accepted-manual.json';
  if(existsSync(join(root,manualPath))) {
    const hash=sha256File(join(root,manualPath));
    if(db.prepare(`SELECT 1 FROM run_input_snapshot i JOIN run r ON r.id=i.run_id JOIN task t ON t.id=r.task_id
      WHERE t.workflow_id=? AND r.status='exited' AND i.manual_values_sha256=?`).get(source.workflowId,hash))generated.set(manualPath,hash);
  }
  for(const stage of source.definition.stages.filter(s=>!['intake','plan','environment','setup'].includes(s.id))) {
    const producer=db.prepare(`SELECT r.result_json FROM run r JOIN task t ON t.id=r.task_id
      WHERE t.workflow_id=? AND t.stage_id=? AND r.status='exited' ORDER BY r.rowid DESC LIMIT 1`).get(source.workflowId,stage.id);
    if(!producer)continue;const hashes=producer.result_json?JSON.parse(String(producer.result_json)).verifiedArtifactHashes??{}:{};
    for(const kind of stage.produces) {const spec=source.capabilities.artifacts[kind];if(spec&&hashes[kind]&&artifactFingerprint(root,spec)===hashes[kind])
      for(const path of artifactFiles(root,spec))generated.set(path,sha256File(join(root,path)));}
  }
  return [...generated].map(([path,sha256])=>({path,sha256}));
}

/** Only unchanged, content-bound approval can seed a rebuild. No planning executor is invoked. */
function seedFiles(db:DatabaseSync,source:WorkflowSnapshot,target:WorkflowSnapshot,root:string):ProductionFile[] {
  const hashes=buildAggregateInput(db,source.workflowId).artifactHashes, files=new Map<string,string>();
  for(const asset of source.manifest?.assets??[]) {
    const path=relativeInside(root,asset.item);if(path!==undefined&&asset.sha256)files.set(path,asset.sha256);
  }
  const state=aggregateWorkflow(db,source.workflowId,source.definition);
  for(const stageId of ['intake','plan']) {
    const stage=source.definition.stages.find(s=>s.id===stageId);if(!stage)continue;
    const next=target.definition.stages.find(s=>s.id===stageId);
    if(!next || !equal(stage,next) || state.stages[stageId]?.status!=='passed')conflict('原清点或批准方案无法按相同合同核验，重建没有重新规划。');
    for(const gateId of stage.gates)if(!equal(source.definition.gates.find(g=>g.id===gateId),target.definition.gates.find(g=>g.id===gateId)))conflict('原批准决定的含义已变化，需要先核对。');
    for(const checkId of stage.requires) {
      const before=source.definition.checks.find(c=>c.id===checkId),after=target.definition.checks.find(c=>c.id===checkId);
      if(!before || !equal(before,after) || !equal(source.capabilities.observers[before.observe],target.capabilities.observers[before.observe]))conflict('清点或方案检查合同已变化，需要独立复验后再重建。');
    }
    if(!equal(preparationEvidenceContract(source,stageId),preparationEvidenceContract(target,stageId)))conflict('批准准备证据所依赖的观察合同已变化，需要独立复验。');
    for(const kind of stage.produces) {
      const spec=source.capabilities.artifacts[kind];
      if(!spec || !equal(spec,target.capabilities.artifacts[kind]) || !hashes[kind] || artifactFingerprint(root,spec)!==hashes[kind])conflict('原批准清点或方案文件已缺失或变化，不能重建。');
      for(const path of artifactFiles(root,spec))files.set(path,sha256File(join(root,path)));
    }
  }
  // A verified environment lock carries the historical custom template bytes. Its prepare unit re-verifies this copy.
  const environment=source.capabilities.artifacts.environment;
  if(environment && equal(environment,target.capabilities.artifacts.environment) && hashes.environment
    && artifactFingerprint(root,environment)===hashes.environment
    && source.tools['harness/environment-recipe.json']===target.tools['harness/environment-recipe.json'])
    for(const path of artifactFiles(root,environment))files.set(path,sha256File(join(root,path)));
  return [...files].map(([path,sha256])=>({path,sha256})).sort((a,b)=>a.path.localeCompare(b.path));
}

function reuseSeeds(db:DatabaseSync,row:Continuation,source:WorkflowSnapshot,target:WorkflowSnapshot,workflowId:string,root:string) {
  for(const stageId of ['intake','plan']) {
    const stage=target.definition.stages.find(s=>s.id===stageId);if(!stage)continue;
    const completion=db.prepare(`SELECT c.seq,c.artifact_hashes_json,r.result_json FROM stage_completion c
      LEFT JOIN run r ON r.id=c.run_id WHERE c.workflow_id=? AND c.stage_id=? ORDER BY c.seq DESC LIMIT 1`).get(source.workflowId,stageId);
    const archived=!completion?db.prepare('SELECT * FROM production_archived_evidence WHERE workflow_id=? AND stage_id=?').get(source.workflowId,stageId):undefined;
    if(!completion&&!archived)conflict('批准准备阶段的完成来源缺失，不能重建。');
    const proof=archived?JSON.parse(String(archived.proof_json)):undefined;
    const hashes=proof?{...proof.outputHashes,...proof.artifactHashes}:{...(completion!.result_json?JSON.parse(String(completion!.result_json)).verifiedArtifactHashes??{}:{}),...JSON.parse(String(completion!.artifact_hashes_json))};
    for(const kind of [...stage.produces,...stage.invalidated_by]) {
      const spec=target.capabilities.artifacts[kind],hash=spec&&artifactFingerprint(root,spec);
      if(!hash || hashes[kind]!==hash)conflict('重建播种内容与原批准输入不同。');
      db.prepare('INSERT INTO artifact_version(workflow_id,kind,hash) VALUES(?,?,?)').run(workflowId,kind,hash);
    }
    if(archived)db.prepare('INSERT INTO production_archived_evidence VALUES(?,?,?,?,?,?)').run(workflowId,stageId,archived.source_workflow_id!,archived.source_completion_seq!,archived.proof_json!,archived.proof_sha256!);
    else db.prepare('INSERT INTO production_evidence_reuse VALUES(?,?,?,?)').run(workflowId,stageId,source.workflowId,completion!.seq!);
  }
}

/** Build an unpublished complete Workflow using original inputs; the Scheduler runs only environment/setup. */
export async function advanceFrozenRebuild(db:DatabaseSync,config:LocalConfig,row:Continuation,source:WorkflowSnapshot,mayContinue:()=>boolean) {
  let preparation:RebuildPreparation|undefined=row.preparation_json?JSON.parse(row.preparation_json):undefined;
  const chosen=db.prepare('SELECT * FROM production_continuation_contract WHERE continuation_id=? ORDER BY event_seq DESC LIMIT 1').get(row.id);
  if(!row.target_revision_id && !chosen)conflict('旧制作的输入合同需要显式采用后继制作版本；旧执行和交付保留。');
  const target=chosen?JSON.parse(String(chosen.snapshot_json)) as WorkflowSnapshot:source;
  if(chosen) {
    const pack=managedPacks(config.home).find(p=>p.id===chosen.pack_id);
    if(!pack || packTreeHash(pack.root).hash!==chosen.pack_hash || inputSha256(canonicalJson(source))!==chosen.source_hash)conflict('已采用制作版本或原冻结合同的内容变化，未改用其他版本。');
  }
  // The idle verdict is three table scans and this guard is consulted per copied file; the caller's own conditions
  // stay per file, only the repeated database verdict is reused inside its window.
  const projectIdle=idleOnCadence(()=>productionProjectIdle(db,row.predecessor_project_id));
  const current=()=>mayContinue() && projectIdle()
    && db.prepare('SELECT state FROM production_continuation INDEXED BY production_continuation_state WHERE id=?').get(row.id)?.state==='preparing'
    && db.prepare('SELECT workflow_id FROM production_head WHERE logical_project_id=?').get(row.logical_project_id)?.workflow_id===row.predecessor_workflow_id;
  if(!preparation) {
    if(!source.manifest?.assets.length || !source.manifest.assets.every(a=>a.sha256))conflict('历史制作缺少冻结素材身份，等待补齐内容后重建。');
    for(const asset of source.manifest.assets) {
      if(!existsSync(asset.item)||!lstatSync(asset.item).isFile()||lstatSync(asset.item).isSymbolicLink()||sha256File(asset.item)!==asset.sha256)
        conflict(`原批准素材缺失或变化，需要恢复相同内容：${asset.name??asset.item}`);
    }
    verifyTools(target.toolRoot,target.tools,Object.keys(target.tools));
    const root=projectRoot(db,row.predecessor_project_id);
    preparation={schema:'production-preparation/0.2',sourceKind:'frozen_rebuild',checkpoint:'preserve',source:root,
      destination:join(config.workspaceRoot,`continuation-${row.id}`),preservedRoot:join(config.home,'production','rebuilds',row.id,'predecessor'),
      sourceFiles:productionFilesAt(root,true),seedFiles:seedFiles(db,source,target,root),snapshot:target,
      contractMode:chosen?'successor':'inherit',sourceContractHash:inputSha256(canonicalJson(source))};
    db.prepare("UPDATE production_continuation SET state='preparing',preparation_json=?,error=NULL WHERE id=? AND state IN ('requested','waiting','failed')").run(JSON.stringify(preparation),row.id);
  } else if(preparation.sourceKind!=='frozen_rebuild')conflict('续接准备来源与历史重建不同，原清单保留。');
  else db.prepare("UPDATE production_continuation SET state='preparing',error=NULL WHERE id=? AND state IN ('requested','waiting','failed')").run(row.id);
  if(!current())return;
  if(preparation.checkpoint==='preserve') {
    await copyProductionManifest(preparation.source,preparation.preservedRoot,preparation.sourceFiles,current);
    if(!equal(productionFilesAt(preparation.source,true),preparation.sourceFiles))conflict('保存历史工程期间内容发生变化，原现场保留。');
    if(!existsSync(join(preparation.preservedRoot,'.git')))execFileSync(hostPlatform.toolCommand('git'),['init','-q',preparation.preservedRoot]);
    preparation.checkpoint='seed';save(db,row,preparation);
  }
  if(preparation.checkpoint==='seed') {
    await copyProductionManifest(preparation.preservedRoot,preparation.destination,preparation.seedFiles,current);
    if(!current())return;
    mkdirSync(preparation.destination,{recursive:true});
    if(!existsSync(join(preparation.destination,'.git')))execFileSync(hostPlatform.toolCommand('git'),['init','-q',preparation.destination]);
    inTransaction(db,()=>{
      if(!current())conflict('历史重建要求已变化，准备内容保留。');
      const projectId=randomUUID(),workflowId=randomUUID(),old=db.prepare('SELECT * FROM project WHERE id=?').get(row.predecessor_project_id)!;
      db.prepare(`INSERT INTO project(id,workspace_id,kind,path,identity_json,lifecycle,harness_version,knowledge_version) VALUES(?,?,?,?,?,'active',?,?)`)
        .run(projectId,old.workspace_id!,old.kind!,preparation!.destination,old.identity_json!,old.harness_version!,old.knowledge_version!);
      forkFrozenWorkflow(db,row.predecessor_workflow_id,projectId,workflowId,relocateProductionAssets(preparation!.snapshot,preparation!.source,preparation!.destination,preparation!.seedFiles));
      if(preparation!.contractMode==='inherit')for(const selected of db.prepare("SELECT entity_id,payload_json FROM event WHERE workflow_id=? AND actor='human' AND entity_type='stage_contract' AND action='selected' ORDER BY seq").all(row.predecessor_workflow_id)) {
        const payload=JSON.parse(String(selected.payload_json));
        payload.selection.snapshot={...relocateProductionAssets(payload.selection.snapshot,preparation!.source,preparation!.destination,preparation!.seedFiles),workflowId};
        withStateEvent(db,{workflowId,actor:'human',entityType:'stage_contract',entityId:String(selected.entity_id),action:'selected',reason:'历史重建继承原已批准工具选择',payload},()=>{});
      }
      db.prepare('UPDATE production_continuation SET successor_project_id=?,successor_workflow_id=? WHERE id=?').run(projectId,workflowId,row.id);
      const input=JSON.parse(row.input_json);
      if(input.manualSessionId)db.prepare('INSERT INTO face_manual_binding VALUES(?,?,?)').run(projectId,input.manualSessionId,row.id);
      activateFaceInput(db,workflowId,{activationId:row.activation_id,mode:input.mode==='ai'?'design':input.mode==='manual'&&input.manualSessionId?'manual':'preserve',manualSessionId:input.manualSessionId});
      reuseSeeds(db,row,source,preparation!.snapshot,workflowId,preparation!.destination);
      preparation!.candidateProjectId=projectId;preparation!.candidateWorkflowId=workflowId;preparation!.checkpoint='prepare';save(db,row,preparation!);
    });
  }
  if(preparation.checkpoint==='prepare') {
    const workflowId=preparation.candidateWorkflowId!,snapshot=workflowSnapshot(db,workflowId),state=aggregateWorkflow(db,workflowId,snapshot.definition);
    const failure=db.prepare(`SELECT t.stage_id,t.status FROM task t WHERE t.workflow_id=? AND t.status IN ('FAILED','BLOCKED','RECOVERY_REQUIRED','CANCELLED')
      AND NOT EXISTS(SELECT 1 FROM task newer WHERE newer.workflow_id=t.workflow_id AND newer.stage_id=t.stage_id AND newer.rowid>t.rowid)
      AND (t.status='RECOVERY_REQUIRED' OR NOT EXISTS(SELECT 1 FROM event redo WHERE redo.entity_type='task' AND redo.entity_id=t.id AND redo.actor='human' AND redo.action='requested_redo'
        AND redo.seq>(SELECT COALESCE(MAX(ended.seq),0) FROM event ended WHERE ended.entity_type='task' AND ended.entity_id=t.id AND (ended.action LIKE '%->FAILED' OR ended.action LIKE '%->CANCELLED' OR ended.action LIKE '%->BLOCKED'))))
      ORDER BY t.rowid DESC LIMIT 1`).get(workflowId);
    if(failure)conflict(`重建准备尚未通过：${failure.stage_id} ${failure.status}，原工程和交付保留。`);
    if(!snapshot.definition.stages.filter(s=>['environment','setup'].includes(s.id)).every(s=>state.stages[s.id]?.status==='passed'))return;
    if(!productionProjectIdle(db,preparation.candidateProjectId!))return;
    const candidate=new Map(productionFilesAt(preparation.destination).map(f=>[f.path,f.sha256])),generated=new Map<string,string>();
    for(const file of verifiedGeneratedFiles(db,row.predecessor_project_id,source,preparation.preservedRoot))generated.set(file.path,file.sha256);
    const unknown=preparation.sourceFiles.filter(f=>candidate.get(f.path)!==f.sha256 && generated.get(f.path)!==f.sha256);
    const report={unknown,candidateFiles:productionFilesAt(preparation.destination),generated:[...generated].map(([path,sha256])=>({path,sha256}))};
    preparation.report={...report,hash:inputSha256(canonicalJson(report))};preparation.checkpoint='reconcile';save(db,row,preparation);
  }
  if(preparation.checkpoint==='reconcile') {
    if(preparation.report!.unknown.length && (!preparation.resolutions || preparation.resolutions.reportHash!==preparation.report!.hash))return;
    if(!equal(productionFilesAt(preparation.destination),preparation.report!.candidateFiles))conflict('对账后的候选工程已变化，旧报告不能批准这些新内容。');
    if(!equal(productionFilesAt(preparation.source,true),preparation.sourceFiles))conflict('对账期间原工程出现新修改，等待核对；不会发布旧报告。');
    preparation.checkpoint='publish';save(db,row,preparation);
  }
  if(preparation.checkpoint==='publish') {
    if(!equal(productionFilesAt(preparation.destination),preparation.report!.candidateFiles)||!equal(productionFilesAt(preparation.source,true),preparation.sourceFiles))conflict('发布前工程内容已变化，必须重新核对报告。');
    return preparation;
  }
}

/** Explicitly retain unexplained edits in the original instead of quietly omitting them from a new delivery. */
export function resolveRebuildChanges(db:DatabaseSync,projectId:string,continuationId:string,revision:number,reportHash:string,retainOnly:string[],note:string) {
  return inTransaction(db,()=>{
    const row=db.prepare('SELECT * FROM production_continuation WHERE id=? AND logical_project_id=?').get(continuationId,projectId) as Continuation|undefined;
    if(!row || row.state!=='preparing'||!row.preparation_json || db.prepare('SELECT revision FROM face_preference WHERE project_id=?').get(projectId)?.revision!==revision)conflict('制作要求已更新，请查看最新对账。');
    const preparation=JSON.parse(row!.preparation_json!) as RebuildPreparation;
    if(preparation.checkpoint!=='reconcile'||preparation.report?.hash!==reportHash||!note.trim()||!equal([...retainOnly].sort(),preparation.report.unknown.map(f=>f.path).sort()))conflict('必须核对完整报告并明确哪些修改仅保留在旧工程，不进入新交付。');
    const event=db.prepare("INSERT INTO event(actor,entity_type,entity_id,action,reason,payload_json) VALUES('human','production_continuation',?,'changes_resolved',?,?) RETURNING seq").get(continuationId,note,JSON.stringify({reportHash,retainOnly}))!;
    preparation.resolutions={reportHash,eventSeq:Number(event.seq),retainOnly};save(db,row!,preparation);
    return {confirmed:true};
  });
}

export function resumeRebuildPreparation(db:DatabaseSync,row:Continuation) {
  const preparation=row.preparation_json?JSON.parse(row.preparation_json):undefined;
  if(preparation?.sourceKind!=='frozen_rebuild'||!preparation.candidateWorkflowId)return;
  if(!productionProjectIdle(db,preparation.candidateProjectId))conflict('准备执行仍有未确认结果，必须先恢复核对，不能直接重做。');
  for(const task of db.prepare("SELECT t.id FROM task t WHERE workflow_id=? AND status IN ('FAILED','BLOCKED','CANCELLED') AND NOT EXISTS(SELECT 1 FROM task newer WHERE newer.workflow_id=t.workflow_id AND newer.stage_id=t.stage_id AND newer.rowid>t.rowid)").all(preparation.candidateWorkflowId))
    taskRedo(db,String(task.id),'Continue confirmed unpublished preparation using the same frozen inputs');
}

export function continuationContracts(config:LocalConfig) {
  return managedPacks(config.home).filter(pack=>pack.channel==='builtin').map(pack=>({id:pack.id,version:pack.version,description:pack.description}));
}

/** A reviewed target is an explicit installed package, independent of the currently active one. */
export function continuationContractView(db:DatabaseSync,config:LocalConfig,projectId:string,continuationId:string,packId:string) {
  const row=db.prepare('SELECT * FROM production_continuation WHERE id=? AND logical_project_id=?').get(continuationId,projectId) as Continuation&{revision:number}|undefined;
  if(!row || ['applied','superseded','cancelled'].includes(row.state) || row.successor_workflow_id)conflict('这次续接已完成、停止或开始准备；不能热换准备合同。');
  const pack=managedPacks(config.home).find(p=>p.id===packId&&p.channel==='builtin');
  if(!pack)conflict('需要选择已安装的正式制作版本。');
  const source=workflowSnapshot(db,row.predecessor_workflow_id),chosen=frozenPackConfig(config,pack,source.profile),definition=chosen.definitions[source.profile]!,capabilities=chosen.capabilities[source.profile]!;
  if(capabilities.artifacts.face_input?.source?.kind!=='runtime' || !definition.stages.find(s=>s.id==='face')?.invalidated_by.includes('face_input')
    || definition.stages.some(s=>!['intake','plan','environment','setup'].includes(s.id)&&!s.invalidated_by.includes('face_input')))
    conflict('该制作版本没有完整的脸型输入与后继失效合同。');
  const tools=Object.fromEntries(manifestToolReferences(capabilities).map(path=>[path,sha256File(join(chosen.toolRoot,path))]));
  const contexts=Object.fromEntries([...new Set(Object.values(capabilities.stages).flatMap(s=>s.context.map(c=>c.path)))].map(path=>{
    const content=readFileSync(join(chosen.knowledgeRoot,path),'utf8');return[path,{sha256:inputSha256(content),content}];
  }));
  const snapshot:WorkflowSnapshot={...source,definition,capabilities,thresholds:chosen.thresholdValues,tools,contexts,toolRoot:chosen.toolRoot};
  const sourceHash=inputSha256(canonicalJson(source)),packHash=packTreeHash(pack.root).hash;
  const changes=definition.stages.filter(s=>!equal(s,source.definition.stages.find(old=>old.id===s.id))||!equal(capabilities.stages[s.id],source.capabilities.stages[s.id])).map(s=>s.id);
  const contracts={before:{definition:source.definition,capabilities:source.capabilities,thresholds:source.thresholds},after:{definition,capabilities,thresholds:chosen.thresholdValues}};
  const token=inputSha256(canonicalJson({continuationId,revision:row.revision,input:row.input_json,sourceHash,packId,packHash,snapshot}));
  return {packId,packHash,sourceHash,token,snapshot,changes,contracts};
}

export function adoptContinuationContract(db:DatabaseSync,config:LocalConfig,projectId:string,continuationId:string,revision:number,packId:string,token:string,note:string) {
  return inTransaction(db,()=>{
    if(db.prepare('SELECT revision FROM face_preference WHERE project_id=?').get(projectId)?.revision!==revision)conflict('脸型要求已更新，请重新核对制作版本。');
    const view=continuationContractView(db,config,projectId,continuationId,packId);
    if(view.token!==token || !note.trim())conflict('目标制作版本或准备状态已变化，请重新核对。');
    const event=db.prepare(`INSERT INTO event(actor,entity_type,entity_id,action,reason,payload_json)
      VALUES('human','production_continuation',?,'contract_adopted',?,?) RETURNING seq`).get(continuationId,note,JSON.stringify({packId,packHash:view.packHash,sourceHash:view.sourceHash,token,changes:view.changes}))!;
    db.prepare('INSERT INTO production_continuation_contract VALUES(?,?,?,?,?,?,?)').run(event.seq!,continuationId,view.sourceHash,packId,view.packHash,JSON.stringify(view.snapshot),token);
    db.prepare("UPDATE production_continuation SET state='requested',preparation_json=NULL,error=NULL,revision=revision+1 WHERE id=?").run(continuationId);
    return {confirmed:true};
  });
}
