import { spawn } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { UnityConfig } from './config.ts';
import { configuredUnityEditor } from './exec/unity-launcher.ts';
import { unityEditorProblem } from './unity-editors.ts';

const opener=`// Generated by Avatar Harness. Opens only the official VRChat SDK panel; it never uploads or handles credentials.\n#if UNITY_EDITOR\nusing UnityEditor;\n[InitializeOnLoad]\npublic static class AVHOpenOfficialVrcSdkPanel {\n  static AVHOpenOfficialVrcSdkPanel() { EditorApplication.delayCall += Open; }\n  static void Open() {\n    if (SessionState.GetBool("AVH.VRCPanelOpened", false)) return;\n    SessionState.SetBool("AVH.VRCPanelOpened", true);\n    EditorApplication.ExecuteMenuItem("VRChat SDK/Show Control Panel");\n  }\n}\n#endif\n`;
export function prepareOfficialUpload(project:string,unity:UnityConfig):{pid:number;helper:string}{
  const manifest=join(project,'Packages','vpm-manifest.json');if(!existsSync(manifest))throw new Error('工程没有 VPM 清单；请先通过 VPM 安装并解析官方 VRChat SDK');
  let dependencies:Record<string,unknown>={};try{dependencies=(JSON.parse(readFileSync(manifest,'utf8')) as {dependencies?:Record<string,unknown>}).dependencies??{};}catch{throw new Error('VPM 清单无法解析');}
  if(!Object.keys(dependencies).some(id=>id==='com.vrchat.avatars'||id==='com.vrchat.worlds'))throw new Error('VPM 清单没有官方 VRChat SDK 包；请先添加并解析对应 SDK');
  const helper=join(project,'Assets','_Harness','Upload','Editor','AVHOpenOfficialVrcSdkPanel.cs');mkdirSync(join(project,'Assets','_Harness','Upload','Editor'),{recursive:true});writeFileSync(helper,opener);
  // The editor itself, not a legacy launcher script: a script takes other arguments and would fail after spawning.
  const editor=configuredUnityEditor(unity),problem=unityEditorProblem(editor);if(problem)throw new Error(`Unity 编辑器不可用：${problem}`);
  const child=spawn(editor,['-projectPath',project],{detached:true,stdio:'ignore'});child.unref();if(!child.pid)throw new Error('Unity 启动失败');return{pid:child.pid,helper};
}
