/**
 * The avatar dictionary Harness starts from: canonical names, the other spellings that mean the same avatar, bodies
 * that avatars share, and words that look like names in BOOTH data but are not avatars (bundles, platforms, series).
 *
 * Imported with the owner's approval from the seed dictionary of the reference project (booth-archiver,
 * backend/booth_archiver/data/avatars.yaml at commit 5a93439). Only the data was carried over: the notes in that file
 * describe one private archive and quote product pages, so they stay out. Ownership and body product ids are never
 * part of the seed; Harness learns them from the person's own BOOTH library, and a person's additions and decisions
 * live in their state database (see avatars.ts), never in this file.
 *
 * Matching folds text first (NFKC, case, katakana to hiragana), so an alias is only needed where folding cannot reach:
 * another script, another spelling, or the long vowel mark ー, which is not folded.
 */
export interface AvatarSeedEntry { canonical: string; aliases: string[]; sharesBodyWith?: string[] }
export interface AvatarSeed { schema: 'harness-avatar-seed/1'; source: string; avatars: AvatarSeedEntry[]; notAvatars: string[] }

export const AVATAR_SEED: AvatarSeed = {
  schema: 'harness-avatar-seed/1',
  source: 'booth-archiver 5a93439 data/avatars.yaml',
  avatars: [
    { canonical: 'Shinano', aliases: ['しなの'] },
    { canonical: 'Sio', aliases: ['しお', 'シオ'] },
    { canonical: 'Eku', aliases: ['エク'] },
    { canonical: 'Kumaly', aliases: ['KUMALY', 'クマリー', 'クマリ'] },
    { canonical: 'Rurune', aliases: ['rurune', 'ルルネ'] },
    { canonical: 'LUMINA', aliases: ['ルミナ', 'LUMINA_EX', 'ルミナ3D'] },
    { canonical: 'MANUKA', aliases: ['マヌカ'] },
    { canonical: 'Selestia', aliases: ['SELESTIA', 'セレスティア', 'セレスチア'] },
    { canonical: 'Chocolat', aliases: ['ショコラ', 'しょこら'] },
    { canonical: 'Milfy', aliases: ['ミルフィ'] },
    { canonical: 'Kipfel', aliases: ['キプフェル'] },
    { canonical: 'Ramune', aliases: ['ラムネ', 'ラムネ(えも研)'] },
    { canonical: 'Misaki', aliases: ['みさき', '海咲'] },
    { canonical: 'Kanata', aliases: ['かなた', '彼方'] },
    { canonical: 'Rize', aliases: ['リゼ'] },
    { canonical: 'Mafuyu', aliases: ['まふゆ', '真冬'] },
    { canonical: 'Madeleine', aliases: ['マドレーヌ'] },
    { canonical: 'Lapwing', aliases: ['ラップウィング'] },
    { canonical: 'Kuuta', aliases: ['くうた'] },
    { canonical: 'Mao', aliases: ['mao', '真央'] },
    { canonical: 'Batsu', aliases: ['ばつ'] },
    { canonical: 'ELusion', aliases: ['エルシオン'] },
    { canonical: 'MUMUS', aliases: ['ムムス'] },
    { canonical: 'Kikyo', aliases: ['桔梗', 'ききょう'] },
    { canonical: 'Moe', aliases: ['萌'] },
    { canonical: 'Shinra', aliases: ['森羅', 'しんら'] },
    { canonical: 'Airi', aliases: ['愛莉', '爱莉', 'あいり'] },
    { canonical: 'Chiffon', aliases: ['シフォン'] },
    { canonical: 'Leefa', aliases: ['リーファ'], sharesBodyWith: ['Lunalitt'] },
    { canonical: 'Lime', aliases: ['ライム'] },
    { canonical: 'Flare', aliases: ['フレア'] },
    { canonical: 'Milltina', aliases: ['ミルティナ', 'Miltina'] },
    { canonical: 'Shiratsume', aliases: ['しらつめ'] },
    { canonical: 'Fyuett', aliases: ['フィユエ'] },
    { canonical: 'Anomea', aliases: ['あのめあ'] },
    { canonical: 'Lunalitt', aliases: ['ルーナリット', 'Lunalit'], sharesBodyWith: ['Leefa'] },
    { canonical: 'Rindo', aliases: ['竜胆', 'りんどう'] },
    { canonical: 'Maya', aliases: ['舞夜', 'まや'] },
    { canonical: 'Karin', aliases: ['カリン'] },
    { canonical: 'Minase', aliases: ['水瀬', 'みなせ'] },
    { canonical: 'Hakka', aliases: ['薄荷', 'はっか'] },
    { canonical: 'Imeris', aliases: ['イメリス'] },
    { canonical: 'Sephira', aliases: ['セフィラ'] },
    { canonical: 'Grus', aliases: ['グルス'] },
    { canonical: 'Lasyusha', aliases: ['ラシューシャ'] },
    { canonical: 'Kitsuneyuki', aliases: ['狐雪'] },
    { canonical: 'Anon', aliases: ['あのん'] },
    { canonical: 'Kuromu', aliases: ['クロム'] },
    { canonical: 'Sagiri', aliases: ['さぎり'] },
    { canonical: 'Nina', aliases: ['ニーナ'] },
    { canonical: 'Mizuki', aliases: ['瑞希', 'みずき'] },
    { canonical: 'Ichigo', aliases: ['いちご'] },
    { canonical: 'Plum', aliases: ['ぷらむ'] },
    { canonical: 'Kaguya', aliases: ['輝夜', 'かぐや'] },
    { canonical: 'Mayo', aliases: ['まよ'] },
    { canonical: 'Ririka', aliases: ['りりか'] },
    { canonical: 'Rinasciita', aliases: ['りなしーた'] },
    { canonical: 'Komano', aliases: ['狛乃'] },
    { canonical: 'Suiha', aliases: ['翠羽', 'すいは'] },
    { canonical: 'Yuzuki', aliases: ['柚希', 'ゆずき'], sharesBodyWith: ['Ririsa'] },
    { canonical: 'Reika', aliases: ['霊佳'] },
    { canonical: 'Nagi', aliases: ['凪', 'なぎ'] },
    { canonical: 'Mamehinata', aliases: ['まめひなた'] },
    { canonical: 'Nemesis', aliases: ['ねめしす'] },
    { canonical: 'Kisha', aliases: ['きしゃ'] },
    { canonical: 'Cazalis', aliases: ['かざりす', 'Kazaris'] },
    { canonical: 'Sapphy', aliases: ['さふぃー', 'Saffy'] },
    { canonical: 'Iska', aliases: ['いすか'] },
    { canonical: 'SiuSiu', aliases: [] },
    { canonical: 'Sion', aliases: ['しおん'] },
    { canonical: 'Uruki', aliases: ['うるき'] },
    { canonical: 'Rusk', aliases: ['らすく'] },
    { canonical: 'Hikarun', aliases: ['ひかるん'], sharesBodyWith: ['Ryumii'] },
    { canonical: 'Ryumii', aliases: ['りゅみぃ'], sharesBodyWith: ['Hikarun'] },
    { canonical: 'Yugi', aliases: ['ユギ', 'ユギミヨ', 'YugiMiyo', 'ゆぎみよ'] },
    { canonical: 'Miyo', aliases: ['ミヨ'] },
    { canonical: 'Marycia', aliases: ['まりしあ', 'Malicia', 'Marisia'] },
    { canonical: 'Nehail', aliases: ['ねはいる'] },
    { canonical: 'Savarum', aliases: ['さばらむ', 'Sabaram'] },
    { canonical: 'Wendy', aliases: ['うぇんでぃ'] },
    { canonical: 'Luchika', aliases: ['るちか'] },
    { canonical: 'Caprilina', aliases: ['かぷりぃな', 'Capriina'] },
    { canonical: 'Shiraha', aliases: ['しらは'] },
    { canonical: 'Riru', aliases: ['りる'] },
    { canonical: 'Phenoa', aliases: ['ふぇのあ', 'Phenøa'] },
    { canonical: 'Mie', aliases: ['みえ'] },
    { canonical: 'Miya', aliases: ['みや'] },
    { canonical: 'Utona', aliases: ['うとな'] },
    { canonical: 'Linne', aliases: ['りんね'] },
    { canonical: 'Lunary', aliases: ['るなりぃ'] },
    { canonical: 'Miriam', aliases: ['みりあむ'] },
  ],
  notAvatars: [
    'fullset', 'full set', 'フルセット', '全セット', 'セット', 'set', 'single', 'base',
    'ベース', 'head', '+head', 'body', 'texture', 'テクスチャ', 'gimmick', 'ギミック',
    'おまけ', 'bonus', 'all', '全て', 'その他', 'other', 'dl', 'pdf',
    'vrchat', 'modularavatar', 'ma', 'marubody', '睡眠', '改変', 'こまど', 'こまどアバター',
    'こまどあばたー', 'あまとうさぎアバター', 'まめふれんず', 'mamefriends', 'mame friends', 'あまとうさぎ', 'amatousagi', 'amatousagiavatars',
    'わこーのあとりえ', 'novabody', 'フルパッケージ', 'full package', 'panty',
  ],
};
